defaults:
  -
    scope:
      path: "proto"
    values:
      altLangPage: "#"
      css: https://test.canada.ca/covid-19-guidance/proto/css/alpha-beta-banner.css
      layout: default
      pageclass: cnt-wdth-lmtd
      script: https://test.canada.ca/covid-19-guidance/proto/js/alpha-banner.js
plugins:
  - jekyll-remote-theme
remote_theme: wet-boew/gcweb-jekyll
