defaults:
  -
    scope:
      path: 
      - travel-2.0
      - sandbox
    values:
      altLangPage: "#"
      css: 
      - https://test.canada.ca/covid-19-guidance/proto/css/alpha-beta-banner.css
      - https://test.canada.ca/covid-19-guidance-2021/travel-2.0/css/wizard.css
      layout: default
      script: https://test.canada.ca/covid-19-guidance/proto/js/alpha-banner.js
plugins:
  - jekyll-remote-theme
remote_theme: wet-boew/gcweb-jekyll
